SELECT CName FROM  COMPANY WHERE CId = 3;
SELECT PName FROM PRODUCT WHERE Price > 200 ORDER BY PName;
SELECT SUM(Income) FROM CONSUMER WHERE age > 30;
SELECT AVG(Price) FROM PRODUCT;
SELECT * FROM DISTRIBUTOR WHERE DId = 116;
SELECT PName FROM PRODUCT WHERE Price = (SELECT Max(Price) FROM PRODUCT);
SELECT * FROM PRODUCT WHERE Price BETWEEN 250 AND 750;